#ifndef __PMLB_HPP__
#define __PMLB_HPP__

#include <string>
#include <vector>

namespace datasets {
const std::vector<std::string> class_datasets = {
    "analcatdata_lawsuit",
    "analcatdata_boxing2",
    "heart_c",
    "agaricus_lepiota",
    "horse_colic",
    "australian",
    "flare",
    "phoneme",
    "breast_cancer_wisconsin",
    "analcatdata_creditscore",
    "clean1",
    "monk2",
    "analcatdata_aids",
    "analcatdata_bankruptcy",
    "churn",
    "hypothyroid",
    "lupus",
    "GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1",
    "labor",
    "analcatdata_boxing1",
    "xd6",
    "Hill_Valley_without_noise",
    "corral",
    "adult",
    "molecular_biology_promoters",
    "twonorm",
    "breast_w",
    "bupa",
    "diabetes",
    "chess",
    "german",
    "mux6",
    "backache",
    "tokyo1",
    "ionosphere",
    "prnn_crabs",
    "monk3",
    "mofn_3_7_10",
    "threeOf9",
    "ring",
    "spect",
    "biomed",
    "colic",
    "sonar",
    "hepatitis",
    "cleve",
    "monk1",
    "irish",
    "parity5+5",
    "coil2000",
    "magic",
    "breast_cancer",
    "analcatdata_cyyoung8092",
    "GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1",
    "GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1",
    "postoperative_patient_data",
    "crx",
    "clean2",
    "house_votes_84",
    "dis",
    "haberman",
    "saheart",
    "GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1",
    "GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_50_EDM_2_001",
    "profb",
    "analcatdata_fraud",
    "tic_tac_toe",
    "kr_vs_kp",
    "credit_g",
    "prnn_synth",
    "credit_a",
    "parity5",
    "mushroom",
    "breast",
    "glass2",
    "pima",
    "analcatdata_asbestos",
    "appendicitis",
    "vote",
    "analcatdata_japansolvent",
    "heart_h",
    "GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_75_EDM_2_001",
    "wdbc",
    "buggyCrx",
    "analcatdata_cyyoung9302",
    "hungarian",
    "spambase",
    "spectf",
    "heart_statlog",
    "Hill_Valley_with_noise"};
}  // namespace datasets

class pmlb {
public:
  pmlb() = default;
};

#endif
